"""
Real Carousell category names — the full matching universe for the demo,
SCOPED TO SINGAPORE (country = 'SG').

Source: DISTINCT category_name from
woven-bonbon-90705.db_events_internal.sell_actions
(event list_category_tapped, Jun 1 - Sep 1 2026, country = 'SG'),
restricted to categories tapped at least 10 times in that window and to
ASCII names (a handful of Chinese-script category names exist for SG's
Chinese-speaking users too, just excluded here for demo readability).

Earlier versions of this demo used the GLOBAL category list (all
countries), which meant Indonesian-market categories like "Aksesoris
Mobil" (Car Accessories) and "Barang Yang Dicari" (Wanted Items) showed
up in an otherwise SG-focused demo. This version is scoped to SG only, so
every category name here is one that real Singapore users actually
searched for and tapped.

This is the pool every search is matched against, regardless of which
query you type. Matching always runs against this full list; only the
(query, category) *frequency* is sparse (see real_data.py), and a
missing frequency correctly defaults to 0 rather than the category
disappearing as a candidate.
"""

CATEGORY_UNIVERSE = [
    "Raw Cards", "Watches", "Sneakers", "Tables & Sets", "Toys & Games",
    "Bags & Wallets", "Designer & Blind Box Toys", "Toy Figures", "Graded Cards",
    "Plushies & Soft Toys", "Raw Singles", "Dresses", "Bicycles", "Software",
    "Plants & Seeds", "Shoulder Bags", "Currency", "K-Wave Merchandise",
    "Activewear", "Shelves, Cabinets & Racks (Ready-Made)", "CDs & DVDs",
    "Chairs", "Tshirts & Polo Shirts", "Babies & Kids Fashion",
    "Card Boxes & Cases", "Parts & Accessories", "Sunglasses & Eyewear",
    "Vintage Collectibles", "Bed Frames & Mattresses",
    "Coats, Jackets and Outerwear", "Shirts", "Vehicle & Diecast Models",
    "Cross-body Bags", "Sleeveless", "Figurines & Statues", "Everything Else",
    "Graded Singles", "Character Goods", "Religious Items",
    "Laptops & Notebooks", "Samsung", "Handmade Craft",
    "Shelves, Cabinets & Racks", "Action & Battle Toys", "Blouses",
    "Announcements", "Fragrance & Deodorants", "Men's Watches", "Art & Prints",
    "Lego & Building Sets", "Backpacks", "Homes & Other Pet Accessories",
    "Stamps & Prints", "Bracelets", "Used Cars", "Tote Bags", "Sofas",
    "Event Tickets", "Cameras", "Luggage", "Face Care", "In-Game Products",
    "Comics & Manga", "Soundbars, Speakers & Amplifiers",
    "Motorcycle Accessories", "Skirts", "Racket & Ball Sports", "Shorts",
    "Nintendo", "Other Tops", "Kids Toys", "Vinyls",
    "Refrigerators & Freezers", "Necklaces", "Room Rentals", "Card Packs",
    "Craft Supplies & Tools", "Painting & Wallpaper", "Other Merchandise",
    "Accessories", "Computer Parts", "Jeans & Leggings",
    "Wallets & Card Holders", "Makeup", "Longsleeves", "iPhone 17 Series",
    "Musical Instruments", "Stationery & School Supplies",
    "Trading Cards Accessories", "Home Improvement Tools & Accessories",
    "Others", "Water Bottles & Tumblers", "HDB", "Lens & Kits", "PlayStation",
    "Flowers & Bouquets", "Storybooks", "Earphones", "Purses & Pouches",
    "J-Wave Merchandise", "Sling Bags", "Washing Machines and Dryers",
    "Other Bottoms", "Desktops", "Wearables & Smart Watches",
    "Cases & Sleeves", "Occasions & Party Supplies", "Rings",
    "Board Games & Puzzles", "Precious Stones", "Children's Books", "Fishing",
    "Earrings", "Hair", "Fans", "Game Gift Cards & Accounts",
    "Bathroom & Kitchen Fixtures", "Breastfeeding & Bottle Feeding", "Golf",
    "TV", "Other Home Furniture", "Infant Playtime", "Sets or Coordinates",
    "Other Sports Equipment and Supplies", "Hiking & Camping",
    "Sneakers & Footwear", "Class 2B", "New Undergarments & Loungewear",
    "Flipflops and Slides", "Cookware & Accessories", "iPad", "Networking",
    "Coffee & Tea Tableware", "Jeans", "Travel Essentials & Accessories",
    "Storage Boxes & Baskets", "Lighting", "Interactive Toys", "Jewelry",
    "Bedding & Towels", "Boots", "Music Accessories",
    "Other Stationery & Craft", "Assessment Books", "Car Rental",
    "Other Accessories", "Beverages", "Apparel", "Medical Supplies & Tools",
    "OPPO", "Gundam Model Kits", "TV Consoles (Ready-Made)", "Carpets & Mats",
    "iPhone 16 Series", "iPhone 15 Series", "Vouchers", "K-Wave",
    "Outdoor Furniture", "E-Scooters & E-Bikes", "Caps & Hats",
    "Computer Keyboard", "Headphones & Headsets",
    "Vacuum Cleaner & Housekeeping", "Monitor Screens", "Vitamins & Supplements",
    "Vases & Decorative Bowls", "Android", "Dinnerware & Cutlery", "Pet Food",
    "Casual shoes", "Class 2", "Controllers", "Other Home Decor",
    "Cables & Adaptors", "Food Organisation & Storage", "Women's Watches",
    "Textbooks", "Other Audio Equipment", "Honor", "Gundam & Model Kits",
    "Alcoholic Beverages", "Office & Business Technology",
    "Printers, Scanners & Copiers", "Body Care", "Used Rims",
    "Educational & Learning Toys", "iPhone 13 Series", "Hoodies",
    "Bodykits & Styling", "Sandals", "iPhone 14 Series", "Used Tyres",
    "Homemade Bakes", "Massage Devices", "Heels", "Wall Decor",
    "Coffee Machines & Makers", "Charms", "Fan Merchandise", "Belts",
    "Hair Accessories", "Mouse & Mousepads", "Class 2A",
    "Other Mobile & Gadget Accessories", "Flats", "Cookers", "Strollers",
    "Trousers", "Artificial Plants & Flowers", "Cardio & Fitness Machines",
    "Chargers & Cables", "Accessory holder, box & organizers",
    "Local Attractions & Transport", "Health & Grooming", "Epoxy Flooring",
    "Weights & Dumbbells", "Xiaomi", "Bathroom & Kitchen Accessories",
    "Scarves", "TV Consoles", "Cleaning Tools & Supplies",
    "Health Food, Drinks & Tonics", "Traditional & Ethnic wear",
    "Hands & Nails", "Air Purifiers & Dehumidifiers",
    "Skates, Rollerblades & Scooters", "Electrical, Adaptors & Sockets",
    "Condos & ECs", "Home Fragrance", "HDB Renovation", "Google Pixel",
    "Power Banks & Chargers", "Remote Control Toys", "Motorcycle Apparel",
    "Billiards & Bowling", "Water Sports", "Other Kitchenware & Tableware",
    "Other Gadgets", "Packaged & Instant Food", "TV Parts & Accessories",
    "Face Care Products", "Belt bags, Clutches and Pouches", "Pots & Planters",
    "Commercial", "Evening dresses & gowns", "Bodywork & Spray Painting",
    "Maternity Care", "Diapers & Baby Wipes", "Ovens & Toasters", "Mirrors",
    "Hard Disks & Thumbdrives", "Other Photography Accessories",
    "Android Others", "Laptop Bags & Sleeves", "Weaning & Toddler Feeding",
    "Enrichment & Tuition", "iPhone 12 Series", "Mounts & Holders",
    "New Underwear", "Juicers, Blenders & Grinders", "Cots & Cribs",
    "Looking For", "Rompers", "Other Food & Drinks", "Locks, Doors & Gates",
    "Vivo", "Other Home Appliances", "Tops", "Other Car Services",
    "Video Cameras", "Other Kitchen Appliances", "Printing, Design & Marketing",
    "Hats & Beanies", "Makeup Products", "Magazines", "Jumpsuits",
    "Air Conditioners & Heating", "Fiction & Non-Fiction", "Oral Care",
    "Gift Baskets & Hampers", "Hijabs", "Other Car Parts",
    "Portable Audio Accessories", "Kids' Tables & Chairs", "Cushions & Throws",
    "Sanitary Hygiene", "Clothes Drying Rack", "Projectors", "Car Seats",
    "Bath", "Microphones", "Hair Products", "Xbox", "Carriers & Slings",
    "Tools & Equipment", "Storage & Organization", "Engine",
    "Toning & Stretching Accessories", "Local Eats",
    "Sports & Fitness Nutrition", "Irons & Steamers", "Western Merchandise",
    "Portable Music Players", "Camera Bags & Carriers", "Frames & Pictures",
    "Hooks & Hangers", "Lighting & Studio Equipment", "Clutches",
    "Bikinis & Swimsuits", "Bakeware", "Dress Shoes", "Parquet Flooring",
    "Socks & Tights", "Used Commercial Vehicles for Sale",
    "Tripods & Monopods", "Wall Decor Accessories",
    "Drywall Partition & False Ceiling", "BBQ, Grills & Hotpots",
    "Water Purifers & Dispensers", "Braces, Support & Protection",
    "Religion Books", "Health Monitors & Weighing Scales", "New Tyres",
    "Fryers", "Drones", "Loafers", "Briefcases",
    "Entertainment Systems & Smart Home Devices",
    "Photography & Video Services", "Beauty & Health Services",
    "Audio Systems", "Wheelchairs", "Other Home Decor Accessories",
    "Event & Party Services", "Baju Kurung & sets", "iPhone Air Series",
    "Batteries & Chargers", "Other Electronics",
    "Flights & Overseas Attractions", "Childrens' Beds",
    "Gardening Tools & Ornaments", "Sim Cards", "Kettles & Airpots",
    "Media Streamers & Hubs", "Socks", "Joggers", "Interior Styling & Trim",
    "Curtains & Blinds", "Sets & Coordinates", "Adult Incontinence", "Used",
    "License Plate Numbers", "Cameras & Sensors", "Exterior Lighting",
    "Admin, Finance, Legal", "Vision Care", "Clocks", "Suspension & Handling",
    "Other Babies Going Out Needs", "Diaper Bags & Wetbags",
    "iPhone 11 Series", "Brooches", "Chargers", "Security Systems & CCTV Cameras",
    "Maternity wear", "Men's Grooming", "New Rims", "Baby Toiletries & Grooming",
    "Body Jewelry", "Cleaning & Detailing Products", "General Servicing",
    "Rehabilitative Devices", "Handyman and Drilling Services", "E-Readers",
    "Knives & Chopping Boards", "Safety Gates, Locks & Protectors",
    "Locks, Doors & Gates (Ready-made)", "Bathtub & Bath Accessories",
    "Memory & SD Cards", "Property - Others", "Fluids & Additives",
    "Sun Shades & Shields", "Shoe inserts & accessories",
    "Clothes Drying Rack (Self-Installed)", "Brakes", "J-pop",
    "Baby High Chairs", "Navigation & Displays", "Chilled & Frozen Food",
    "Wheel Accessories", "Kaftans & Jubahs", "iPhone X Series", "Infinix",
    "Umbrellas", "Huawei", "Seats & Cabin", "Store Credits",
    "Ladders & Steps", "Hobs & Hoods", "Sport & Fitness Classes",
    "Music Scores", "Professional Skills", "Toilet Renovation",
    "Cases & Covers", "IT & Programming", "Steering Wheel",
    "Other PMDs & Parts", "Laundry Baskets", "Transport & Delivery",
    "Health & Grooming Supplies", "Face Masks & Face Shields",
    "Waste Bins & Bags", "Floor & Mats", "Waterproofing & Treatment",
    "Baby Monitors", "Wine Cellar & Storage", "Exercise Mats",
    "Early Generation Mobile Phones", "Virtual Reality",
    "Other Kids Furniture", "Detergents", "Water Heater & Instant Showers",
    "Racks & Protection", "OnePlus", "Landed Property",
    "Pitchers & Dispensers", "Detailing & Protection", "Hand & Stand Mixers",
    "Towels, Napkins & Holders", "Vinyl Flooring", "Stones, Pavers & Decks",
    "Other Vehicles", "Pet Care Services", "iPhone SE Series",
    "Garden Soil & Fertilisers", "Gimbals & Stabilisers",
    "Motorcycle Rental", "Electrician Services", "Table Linen & Textiles",
    "Spice & Seasoning", "Travel & Holiday Guides", "Foot Care", "Flashes",
    "Exhaust", "Dishwasher", "Swim Trunks & Board Shorts",
    "Sales, Retail & Marketing", "Music & Arts Classes", "Fresh Produce",
    "Gloves", "Nothing", "Sanitisers & Disinfectants",
    "Security Systems & CCTV Cameras (Self-Installed)", "Shoe inserts",
    "Basic Home Cleaning", "Rice & Noodles", "Chinos", "Bottoms",
    "Interior Design Services", "iPhone Others", "Beach Bags",
    "Electronics & Gadget Repairs", "Hair Removal", "Dry Boxes & Cabinets",
    "Ties", "Vests", "Plumbing Services", "Nursery Lighting & Decor",
    "Other Baby Bathing & Changing Needs", "Pest Control Supplies",
    "Cables & Chargers", "Mirrors & Wipers", "Blu-Ray & Media Players",
    "Key & Remote", "Safe", "Hose and Watering Devices", "Emergency Tools",
    "Exterior Customization", "Other Assistive Aids", "Education & Training",
    "Commercial Vehicles for Rent", "Kids' Wardrobes & Storage",
    "Portable Air Conditioners & Heaters", "Webcams", "Hospitality, F&B",
    "Photo Frames", "Home Appliances Repair", "Ice-cream Makers",
    "Custom Plates & Accessories", "House Moving", "Carpentry",
    "Ironing Boards", "Wedges", "Ear Care", "Warehouse & Logistics",
    "Voice Recorders", "Computer & IT", "Lighting & Electrical Services",
    "General Repairs", "Internships & Others", "Changing Mats & Accessories",
    "Cleaning", "Soothers & Pacifiers", "Aircon Installation",
    "Courier & Parcel Delivery", "Admin & Finance", "Realme", "Thermometers",
    "Deep Cleaning Services", "Changing Tables & Stations",
    "Customer Service", "New Cars", "Bed Guards", "Sleep and Loungewear",
    "Curtains & Blinds (Ready-Made)", "Recommended Properties", "Battery",
    "Air Conditioning", "Men's Grooming Products", "Cars Specials",
    "Disposal Services", "Rentals", "Caregiving Services",
    "Seatbelts & Safety", "Hands & Nails Accessories", "Insect Repellent",
    "Other Security Devices", "Workshops", "BTO Renovation",
    "Toilet Training", "Transmission & Drivetrain", "Car Rentals",
    "iPhone 6 Series", "ECU", "iPhone 8 Series", "Aircon Repair",
    "Grass Mowers & Trimmers", "Preorders", "Sony",
    "Peephole Viewers & Doorbells", "Breadmakers",
    "Landed Housing Renovation", "Interactive Gaming Figures",
    "iPhone 7 Series", "Prayer Sets", "Fluid & Filter Services",
    "Aluminium Work", "Nursing & Healthcare", "Mobile Battery Replacement",
    "Motorola", "Walkie-Talkie", "Electrical & Electronics", "Cuff Links",
    "Solar Film & Tinting", "Anklets", "Kids' Wardrobes & Storage (Ready-Made)",
    "Furniture Movers", "Beanie", "Asus", "Parallel Imports",
    "Foot Care Products", "CCTV/Security", "Condo Renovation",
    "New Commercial Vehicles for Sale", "Move in/out Cleaning",
    "Other Kids Furniture (Ready-Made)", "New", "Office/Commercial Cleaning",
    "Drycleaning & Laundry", "Ear Care Products", "Post Renovation Cleaning",
    "Handkerchief & Pocket Squares", "Chemical Wash", "Towing & Recovery",
    "Kites", "Valet & Limousine", "Tailoring & Restoration",
    "Mattress Cleaning", "Sofa Cleaning", "Specials",
    "Swim Top & Rash Guards", "Recommended", "Pest Control Services", "LG",
    "Office Movers", "Rash Guard", "Windows", "Visual & Hearing Aids",
    "New Launches", "Overseas", "Upholstery", "Locksmith Services",
    "Chemical Overhaul", "Gas Top-up", "Laminate Flooring",
]

CATEGORY_UNIVERSE = list(dict.fromkeys(CATEGORY_UNIVERSE))
